# Generated by Django 5.0.1 on 2024-02-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExampleModel',
            new_name='Users',
        ),
    ]
