# Generated by Django 5.0.1 on 2024-02-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_rename_examplemodel_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='suscribed',
            field=models.BooleanField(default=False),
        ),
    ]
